config/routes.rb
Rails.application.routes.draw do

  resources :games
  root 'welcome#index'  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'logout', to: 'sessions#destroy', as: 'logout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :videos, only: [:index, :new, :create]


end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
    validates :game_name, presence: true, uniqueness: true
    validates :price, presence: true
    validates :year_purchased, length: { is: 4 }

    mount_uploader :image, ImageUploader
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @q = Game.search(params[:q])
    @games = @q.result
  end

  # GET /games/1
  # GET /games/1.json
  def show
    currency_changer = 'https://api.exchangeratesapi.io/latest?base=MYR'
    @currencies = HTTParty.get(currency_changer)['rates']
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game_name, :description, :game_type, :year_purchased, :price, :image)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_name %>
    <%= form.text_field :game_name, placeholder: 'Full game name' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, placeholder: 'whatever' %>
  </div>

  <div class="field">
    <%= form.label :game_type %>
    <%= form.text_field :game_type, placeholder: 'Nintendo? Sony?' %>
  </div>

  <div class="field">
    <%= form.label :year_purchased %>
    <%= form.number_field :year_purchased, placeholder: 'YYYY' %>
  </div>

  <div class="field">
    <%= form.label :price_in_ringgit %>
    <%= form.number_field :price, placeholder: '$ ringgit lah' %>
  </div>

    <div class="field">
    <%= form.label :image_upload %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<div class="pull-right" style="margin-right: 10px">
<%= search_form_for @q, html: {class:"form-inline"} do |f|%>
  <%= f.search_field :game_name_cont, placeholder:"Search", class:"form-control" %>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>Game name</td>
      <td>Year purchased</td>
      <td>Price</td>
    </tr>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.game_name %></td>
        <td><%= game.year_purchased %></td>
        <td><%= game.price %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

<div align="center">
</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>


<%= image_tag @game.image_url(:thumb) if @game.image? %>
<br>
  <ul>
    <li>Game Name :
        <%= @game.game_name %>
    </li>
    <li>Description :
        <%= @game.description %>
    </li>
    <li>Game type :
        <%= @game.game_type %>
    </li>
    <li>Year Purchased : 
        <%= @game.year_purchased %>
    </li>
    <br>

    <%# INCLUDES EXCHANGE RATE API, limit 2 decimals %>
    <li>Price : MYR 
        <%= sprintf('%.2f',@game.price) %>
    </li>
    <li>Price : SGD 
        <%= sprintf('%.2f',@game.price * @currencies['SGD']) %>
    </li>
    <li>Price : USD 
        <%= sprintf('%.2f', @game.price * @currencies['USD']) %>
    </li>
  <ul>
<br>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>