config/routes.rb
Rails.application.routes.draw do

  resources :games
  root 'welcome#index'  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'logout', to: 'sessions#destroy', as: 'logout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :videos, only: [:index, :new, :create]


end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Game Stash', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<%# test %>
<% if signed_in? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'GameList', games_path, class:'nav-link' %>
      </li>

    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
            <%= link_to current_user.name, user_path(current_user.id), class:'nav-link' %>
      </li>
      <li class="nav-item">
            <%= link_to 'Log Out', logout_path, class:"nav-link", method: :destroy %>
      </li>
    </ul>
  </div>

  <% else %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
            <%= link_to 'Log In', login_path, class:"nav-link" %>
      </li>
    </ul>
  </div>
  
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NextAssess</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <%= render 'layouts/header' %>
  <div class = "mx-3">
    <%= yield %>
  </div>
  </body>
</html>